export const featuredProjects = [
    {
      id: 1,
      title: "Finance App",
      img1:"/images/webApp/finance/img1.jpg",
      img2:"/images/webApp/finance/img2.jpg",
      img3:"/images/webApp/finance/img3.jpg",
      img4:"/images/webApp/finance/img4.jpg",
      role: "Developer",
      date: "Jun 25, 2021",
      skills: "React, Sass, Firebase, Material, GitHub",
      url: "https://finance-app-a9684.web.app/login",
      p1:"This app is the financial application. In short, it's the household account book app with login function. As a background story, my motive to develop this app was that my mom used to manege the cash flow by hand writing and it looked like troublesome. And she said that it is difficult to select which application is easy-to-use so that I decided to create simple finance application for her. Of course, this app has been designed for mobile devices like iOS and Android because she usually carry her smartphone and it would be more helpful.",
      p2:"In this project, I implemented user registration function, login function, saving and removing data, and managing financial data by each month(under constructing). For those functions, I implemented by using node, React(Hooks), Firebase(Authentication, Cloud Firestore, Hosting), and CSS/material-ui. As a repository service, I used Git/GitHub to create each branches to suppose that I will be part of the project member. The most difficult part was to handle React hooks(useState, useEffect, useContect), it took almost 3 weeks to learn these concept in React."
    },
    {
      id: 2,
      title: "The Concept Lab",
      img1:"/images/websiteProject/conceptLab/img1.jpg",
      img2:"/images/websiteProject/conceptLab/img2.jpg",
      img3:"/images/websiteProject/conceptLab/img3.jpg",
      img4:"/images/websiteProject/conceptLab/img4.jpg",
      role: "Developer",
      date: "Aug 4, 2021",
      skills: "HTML, Sass, PHP, JavaScript, Figma, Trello, GitHub",
      url: "https://the-concept-lab.takanorifujiki.ca",
      p1:"The Concept Lab is a company of four designers/developers who offer services in creating and maintaining various visual digital media and website development. The purpose of the website is to showcase its portfolio of work, promote its services, and create leads to generate new prospective clients. This is one of group projects in BCIT. We supposed that the targeted clients from small business owner or someone who needs help building a stronger online marketing presence with creating websites and social media presence.",
      p2:"In this project, I was in charge of developer and listed testing tasks to Trello document except for coding in GitHub. Any bugs or issues encountered weere opened as Cards and placed under the Assigned list, and assigned to the Developer to fix. (https://trello.com/b/Ce1oaP7c/qa-concept-lab-qa-checklist) PHP contact mailer function exists at the bottom of the main page and it helps to get the message from clients. Clean and simple home page makes clients focus on the projects. All projects are coded through GitHub repository."
    },
    {
      id: 3,
      title: "Sake Lab",
      img1:"/images/webApp/sakeLab/img1.jpg",
      img2:"/images/webApp/sakeLab/img2.jpg",
      img3:"/images/webApp/sakeLab/img3.jpg",
      img4:"/images/webApp/sakeLab/img4.jpg",
      role: "Developer",
      date: "Aug 07, 2021",
      skills: "JavaScript, Sass, Firebase, Cordova, PHP, Onsen UI",
      url: "",
      p1:"This app name is “Sake Lab”. In this app, user can browse the sake database to find the sake they look for as well as add them to the favorite list they own in accounts. This app consists of 5 main views, including the sign-up view, the home view, item detail views, the favorite-list view, and the setting view. Cross-site Scripting (XSS) exploit a client’s trust in a system. In the sign-in form, there is an input element which could be the security hole. As a countermeasure against this security issues, I used firebase authentication system.",
      p2:"Through the sign-up form, user can create their account and login to the app. From the first viewing, user can access to the sake database to see sake’s information by clicking the detail button. In the item detail view, there are 2 call-to-actions. (Add-to-cart button, Favorite button) The add-to-cart button shows the toast. The favorite buttons will let user transfer to the favorite-list view with the selected item. In the favorite page, there is a remove function at the bottom of item card. In the setting page, user can manage the settings for functions and appearance of the app."
    },
    {
      id: 4,
      title: "Beach Resort",
      img1:"/images/websiteProject/beachResort/img1.jpg",
      img2:"/images/websiteProject/beachResort/img2.jpg",
      img3:"/images/websiteProject/beachResort/img3.jpg",
      img4:"/images/websiteProject/beachResort/img4.jpg",
      role: "Developer",
      date: "May 20, 2021",
      skills: "HTML, CSS, JavaScript, GitHub",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 5,
      title: "Bamaga Dream Store",
      img1:"/images/webApp/bamagaStore/img1.jpg",
      img2:"/images/webApp/bamagaStore/img2.jpg",
      img3:"/images/webApp/bamagaStore/img3.jpg",
      img4:"/images/webApp/bamagaStore/img4.jpg",
      role: "Developer",
      date: "Jun 15, 2021",
      skills: "JavaScript, CSS, Cordova, Onsen UI",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 6,
      title: "Sport Crush",
      img1:"/images/websiteProject/sportCrush/img1.jpg",
      img2:"/images/websiteProject/sportCrush/img2.jpg",
      img3:"/images/websiteProject/sportCrush/img3.jpg",
      img4:"/images/websiteProject/sportCrush/img4.jpg",
      role: "Developer",
      date: "Nov 17, 2020",
      skills: "HTML, CSS, JavaScript",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    }
  ];
  
  export const webApp = [
    {
      id: 1,
      title: "Finance App",
      img1:"/images/webApp/finance/img1.jpg",
      img2:"/images/webApp/finance/img2.jpg",
      img3:"/images/webApp/finance/img3.jpg",
      img4:"/images/webApp/finance/img4.jpg",
      role: "Developer",
      date: "Jun 25, 2021",
      skills: "React, Sass, Firebase, Material, GitHub",
      url: "https://finance-app-a9684.web.app/login",
      p1:"This app is the financial application. In short, it's the household account book app with login function. As a background story, my motive to develop this app was that my mom used to manege the cash flow by hand writing and it looked like troublesome. And she said that it is difficult to select which application is easy-to-use so that I decided to create simple finance application for her. Of course, this app has been designed for mobile devices like iOS and Android because she usually carry her smartphone.",
      p2:"I implemented user registration function, login function, saving and removing data, and managing financial data by each month(under constructing). For those functions, I implemented by using node, React(Hooks), Firebase(Authentication, Cloud Firestore, Hosting), and CSS/material-ui. As a repository service, I used Git/GitHub to create each branches to suppose that I will be part of the project member. The most difficult part was to handle React hooks(useState, useEffect, useContect), it took almost 3 weeks to learn these concept in React."
    },
    {
      id: 2,
      title: "Sake Lab",
      img1:"/images/webApp/sakeLab/img1.jpg",
      img2:"/images/webApp/sakeLab/img2.jpg",
      img3:"/images/webApp/sakeLab/img3.jpg",
      img4:"/images/webApp/sakeLab/img4.jpg",
      role: "Developer",
      date: "Aug 07, 2021",
      skills: "JavaScript, Sass, Firebase, Cordova, PHP, Onsen UI",
      url: "",
      p1:"This app name is “Sake Lab”. In this app, user can browse the sake database to find the sake they look for as well as add them to the favorite list they own in accounts. This app consists of 5 main views, including the sign-up view, the home view, item detail views, the favorite-list view, and the setting view. Cross-site Scripting (XSS) exploit a client’s trust in a system. In the sign-in form, there is an input element which could be the security hole. As a countermeasure against this security issues, I used firebase authentication system.",
      p2:"Through the sign-up form, user can create their account and login to the app. From the first viewing, user can access to the sake database to see sake’s information by clicking the detail button. In the item detail view, there are 2 call-to-actions. (Add-to-cart button, Favorite button) The add-to-cart button shows the toast. The favorite buttons will let user transfer to the favorite-list view with the selected item. In the favorite page, there is a remove function at the bottom of item card. In the setting page, user can manage the settings for functions and appearance of the app."
    },
    {
      id: 3,
      title: "Poke Dex App",
      img1:"/images/webApp/pokeDex/img1.jpg",
      img2:"/images/webApp/pokeDex/img2.jpg",
      img3:"/images/webApp/pokeDex/img3.jpg",
      img4:"/images/webApp/pokeDex/img4.jpg",
      role: "Developer",
      date: "Jun 14, 2021",
      skills: "JavaScript, CSS, Cordova, Onsen UI, Pokemon API",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 4,
      title: "Bamaga Dream Store",
      img1:"/images/webApp/bamagaStore/img1.jpg",
      img2:"/images/webApp/bamagaStore/img2.jpg",
      img3:"/images/webApp/bamagaStore/img3.jpg",
      img4:"/images/webApp/bamagaStore/img4.jpg",
      role: "Developer",
      date: "Jun 15, 2021",
      skills: "JavaScript, CSS, Cordova, Onsen UI",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    }
  ];
  
  export const webSite = [
    {
      id: 1,
      title: "The Concept Lab",
      img1:"/images/websiteProject/conceptLab/img1.jpg",
      img2:"/images/websiteProject/conceptLab/img2.jpg",
      img3:"/images/websiteProject/conceptLab/img3.jpg",
      img4:"/images/websiteProject/conceptLab/img4.jpg",
      role: "Developer",
      date: "Aug 4, 2021",
      skills: "HTML, Sass, PHP, JavaScript, Figma, Trello, GitHub",
      url: "https://the-concept-lab.takanorifujiki.ca",
      p1:"The Concept Lab is a company of four designers/developers who offer services in creating and maintaining various visual digital media and website development. The purpose of the website is to showcase its portfolio of work, promote its services, and create leads to generate new prospective clients. This is one of group projects in BCIT. We supposed that the targeted clients from small business owner or someone who needs help building a stronger online marketing presence with creating websites and social media presence.",
      p2:"In this project, I was in charge of developer and listed testing tasks to Trello document except for coding in GitHub. Any bugs or issues encountered weere opened as Cards and placed under the Assigned list, and assigned to the Developer to fix. (https://trello.com/b/Ce1oaP7c/qa-concept-lab-qa-checklist) PHP contact mailer function exists at the bottom of the main page and it helps to get the message from clients. Clean and simple home page makes clients focus on the projects. All projects are coded through GitHub repository."
    },
    {
      id: 2,
      title: "Beach Resort",
      img1:"/images/websiteProject/beachResort/img1.jpg",
      img2:"/images/websiteProject/beachResort/img2.jpg",
      img3:"/images/websiteProject/beachResort/img3.jpg",
      img4:"/images/websiteProject/beachResort/img4.jpg",
      role: "Developer",
      date: "May 20, 2021",
      skills: "HTML, CSS, JavaScript, GitHub",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 3,
      title: "Sport Crush",
      img1:"/images/websiteProject/sportCrush/img1.jpg",
      img2:"/images/websiteProject/sportCrush/img2.jpg",
      img3:"/images/websiteProject/sportCrush/img3.jpg",
      img4:"/images/websiteProject/sportCrush/img4.jpg",
      role: "Developer",
      date: "Nov 17, 2020",
      skills: "HTML, CSS, JavaScript",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 4,
      title: "JavaScript Learning",
      img1:"/images/websiteProject/jsLearning/img1.jpg",
      img2:"/images/websiteProject/jsLearning/img2.jpg",
      img3:"/images/websiteProject/jsLearning/img3.jpg",
      img4:"/images/websiteProject/jsLearning/img4.jpg",
      role: "Developer",
      date: "Dec 02, 2020",
      skills: "HTML, CSS, JavaScript, jQuery",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 5,
      title: "Photographer Portfolio",
      img1:"/images/websiteProject/photography/img1.jpg",
      img2:"/images/websiteProject/photography/img2.jpg",
      img3:"/images/websiteProject/photography/img3.jpg",
      img4:"/images/websiteProject/photography/img4.jpg",
      role: "Developer",
      date: "Nov 23, 2020",
      skills: "HTML, CSS, JavaScript, jQuery(Accordion, Flickity, Gridder, LightBox)",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
    {
      id: 6,
      title: "Wedding Park",
      img1:"/images/websiteProject/weddingPark/img1.jpg",
      img2:"/images/websiteProject/weddingPark/img2.jpg",
      img3:"/images/websiteProject/weddingPark/img3.jpg",
      img4:"/images/websiteProject/weddingPark/img4.jpg",
      role: "Developer",
      date: "Oct 18, 2020",
      skills: "HTML, CSS, JavaScript, BootStrap",
      url: "",
      p1:"Lorem 1 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim.",
      p2:"Lorem 2 ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie maximus nulla pharetra volutpat. Morbi orci orci, tempor at efficitur ut, feugiat eu arcu. Suspendisse non consectetur nunc. In congue et erat vitae sollicitudin. Fusce quis elit vestibulum, egestas arcu quis, facilisis sem. Nam sodales ligula nec sem euismod sagittis. Mauris ac dignissim ex. Nunc iaculis pharetra dolor, sed pellentesque ex molestie tristique. In vel metus nisl. Maecenas condimentum non dolor a auctor. Duis elementum neque ut lorem posuere dignissim."
    },
  ];
  